"""Add email verification columns

Revision ID: 0244040687ca
Revises: b3799d31e4fe
Create Date: 2026-02-09 20:58:18.803411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0244040687ca'
down_revision = 'b3799d31e4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_verificacion', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['token_verificacion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_verificacion')
        batch_op.drop_column('email_verificado')

    # ### end Alembic commands ###
