"""Initial migration

Revision ID: 1d2a7cfe35d8
Revises: 
Create Date: 2026-02-08 22:34:22.981245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2a7cfe35d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

    op.create_table('proveedores',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('terminos_pago', sa.String(length=100), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedores_nombre'), ['nombre'], unique=False)

    op.create_table('usuarios',
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)

    op.create_table('auditoria_logs',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('valores_anteriores', sa.JSON(), nullable=True),
    sa.Column('valores_nuevos', sa.JSON(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('metodo_http', sa.String(length=10), nullable=True),
    sa.Column('direccion_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_logs_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_logs_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_logs_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_logs_tabla_afectada'), ['tabla_afectada'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_logs_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('productos',
    sa.Column('codigo_sku', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('cantidad_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('stock_maximo', sa.Float(), nullable=True),
    sa.Column('umbral_alerta', sa.Float(), nullable=True),
    sa.Column('costo_promedio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ultimo_costo_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margen_deseado', sa.Float(), nullable=False),
    sa.Column('tiene_vencimiento', sa.Boolean(), nullable=False),
    sa.Column('dias_vencimiento', sa.Integer(), nullable=True),
    sa.Column('alerta_stock_bajo_notificada', sa.Boolean(), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigo_sku'), ['codigo_sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_productos_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=False)

    op.create_table('alertas',
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(length=10), nullable=False),
    sa.Column('esta_resuelta', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('resuelta_por_id', sa.Integer(), nullable=True),
    sa.Column('notas_resolucion', sa.Text(), nullable=True),
    sa.Column('notificada', sa.Boolean(), nullable=False),
    sa.Column('fecha_notificacion', sa.DateTime(), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['resuelta_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_esta_resuelta'), ['esta_resuelta'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_tipo_alerta'), ['tipo_alerta'], unique=False)

    op.create_table('lotes_producto',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=False),
    sa.Column('cantidad_inicial', sa.Float(), nullable=False),
    sa.Column('cantidad_actual', sa.Float(), nullable=False),
    sa.Column('costo_lote', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_producto_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_producto_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_producto_numero_lote'), ['numero_lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_producto_producto_id'), ['producto_id'], unique=False)

    op.create_table('proveedor_producto',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio_compra_habitual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('es_proveedor_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('proveedor_id', 'producto_id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('cantidad_anterior', sa.Float(), nullable=True),
    sa.Column('cantidad_nueva', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('motivo_ajuste', sa.String(length=30), nullable=True),
    sa.Column('referencia_id', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_producto.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_fecha_movimiento'), ['fecha_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_tipo_movimiento'), ['tipo_movimiento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_tipo_movimiento'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_producto_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_fecha_movimiento'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_esta_activo'))

    op.drop_table('movimientos_inventario')
    op.drop_table('proveedor_producto')
    with op.batch_alter_table('lotes_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_producto_producto_id'))
        batch_op.drop_index(batch_op.f('ix_lotes_producto_numero_lote'))
        batch_op.drop_index(batch_op.f('ix_lotes_producto_fecha_vencimiento'))
        batch_op.drop_index(batch_op.f('ix_lotes_producto_esta_activo'))

    op.drop_table('lotes_producto')
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_tipo_alerta'))
        batch_op.drop_index(batch_op.f('ix_alertas_producto_id'))
        batch_op.drop_index(batch_op.f('ix_alertas_esta_resuelta'))
        batch_op.drop_index(batch_op.f('ix_alertas_esta_activo'))

    op.drop_table('alertas')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))
        batch_op.drop_index(batch_op.f('ix_productos_esta_activo'))
        batch_op.drop_index(batch_op.f('ix_productos_codigo_sku'))

    op.drop_table('productos')
    with op.batch_alter_table('auditoria_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_tabla_afectada'))
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_fecha_hora'))
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_esta_activo'))
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_accion'))

    op.drop_table('auditoria_logs')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_esta_activo'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_nombre'))
        batch_op.drop_index(batch_op.f('ix_proveedores_esta_activo'))

    op.drop_table('proveedores')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))
        batch_op.drop_index(batch_op.f('ix_categorias_esta_activo'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
