"""Agregar permite_decimales a Producto

Revision ID: 920385bc1234
Revises: ce7f3d8afc15
Create Date: 2026-04-02 15:49:08.148083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920385bc1234'
down_revision = 'ce7f3d8afc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable first
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permite_decimales', sa.Boolean(), nullable=True))
    
    # 2. Update existing rows to False (default)
    op.execute("UPDATE productos SET permite_decimales = false")
    
    # 3. Set column to NOT NULL
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('permite_decimales', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('permite_decimales')

    # ### end Alembic commands ###
