"""add_product_fractioning_fields

Revision ID: a3d628f4e4a6
Revises: 0244040687ca
Create Date: 2026-02-09 23:16:51.166635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d628f4e4a6'
down_revision = '0244040687ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_padre_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('factor_conversion', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'productos', ['producto_padre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('factor_conversion')
        batch_op.drop_column('producto_padre_id')

    # ### end Alembic commands ###
