"""Add Configuracion model and update Proveedor for RIF

Revision ID: b3799d31e4fe
Revises: 1d2a7cfe35d8
Create Date: 2026-02-09 01:25:55.750434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3799d31e4fe'
down_revision = '1d2a7cfe35d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuraciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuraciones_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_configuraciones_esta_activo'), ['esta_activo'], unique=False)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rif', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('proveedores_ruc_key', type_='unique')
        batch_op.create_unique_constraint(None, ['rif'])
        batch_op.drop_column('ruc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruc', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('proveedores_ruc_key', ['ruc'])
        batch_op.drop_column('rif')

    with op.batch_alter_table('configuraciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuraciones_esta_activo'))
        batch_op.drop_index(batch_op.f('ix_configuraciones_clave'))

    op.drop_table('configuraciones')
    # ### end Alembic commands ###
