"""increase_cost_precision

Revision ID: ce7f3d8afc15
Revises: a3d628f4e4a6
Create Date: 2026-02-09 23:41:22.464348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7f3d8afc15'
down_revision = 'a3d628f4e4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.alter_column('costo_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('costo_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('costo_promedio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
        batch_op.alter_column('ultimo_costo_compra',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('ultimo_costo_compra',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('costo_promedio',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.alter_column('costo_total',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('costo_unitario',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
